notifications:
  email: false
language: cpp
compiler:
  - gcc
addons:
  postgresql: 9.3
before_install:
  - travis_retry sudo add-apt-repository --yes ppa:kalakris/cmake # PPA for cmake > precise 2.8.7
  # Official PostgreSQL repo for libpqtypes
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" >> /etc/apt/sources.list.d/postgresql.list'
  - travis_retry sudo apt-get update -y -qq
  - travis_retry sudo apt-get install cmake
  - travis_retry sudo apt-get install libpqtypes-dev libpqtypes0
install:
  - travis_retry sudo apt-get install -y -qq $(< packagelist-ubuntu-12.04-apt.txt)
script:
  - python setup.py build
